

services:
  copilot:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      HUGGINGFACEHUB_API_TOKEN: 
      
    command: bash -c "rm -rf /app/data/chroma_db/* && python -m streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0"
